### ISSUE TITLE
Unable to use sky-cmp-id when object does not have id field

### ISSUE THREAD

**Issue by Blackbaud-LouisPujol** [blackbaud/skyux-list-builder-view-checklist#34]
### Expected behavior
Would like to provide an object and the field to use for the sky-cmp-id in a sky list view checklist. For example, my email object has email_id and I would like to use that as the sky-cmp-id so that I can utilize the selectedItemsChange method. 

### Actual behavior
Will default to a string with a number on the end that I can use as an index, however, I have to parse the string, I have to hope this naming scheme never changes, and I have to decrement the number to use as an array index because it starts with 1 rather than 0.

### Steps to reproduce
Provide a list of objects with email_id instead of id to a sky-list-view-checklist
Write a selectedItemsChange method and look at the map that is passed in from the $event

### Severity
Medium as this relies on a naming scheme that is not promised to stay the same in the future.

### Impact
Relies on a number of assumptions and any changes to those assumptions will break the app.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-LouisPujol Is there a reason you can't supply an `id` field on your `[data]` object?

**Comment by Blackbaud-LouisPujol** [comment]
It's not an object my team owns. We are using the email object passed to us by the Skymail team. 
I could create an id field and just copy the data from email_id over to id, however, I think it would be preferable to let us use any unique field as the sky-cmp-id.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-LouisPujol Understood. That makes sense.

For scenarios using grid multiselect and checklist, we require an `id` to be present in the `data` object. I think our docs could use some tweaking to make this more clear. I created an issue for that -> https://github.com/blackbaud/skyux2-docs/issues/609.

I think our preferred approach would be to create a new emitter that spits back the selected item instead of the `id` (which, in your scenario is automatically generated and not very useful). That way, you could look at the item object and retrieve the email id from it.

If this sounds like a good approach, lets create a new issue for that. Due to its impact and priority, this is probably something that we'd take contributions on, if you're looking to chip in! :)

FYI - the `sky-cmp-id` property is for internal usage and should not be used by consumers.

**Comment by Blackbaud-LouisPujol** [comment]
@Blackbaud-AlexKingman Ah yes I do like that far approach even more as that sounds like it would protect people from not having a unique id. I'll create a new issue for that and tell my team about it. We have already done our block planning for block 6 so doubtful we could pull that in this block

**Comment by Blackbaud-LouisPujol** [comment]
@Blackbaud-AlexKingman since you have created an issue for the docs update and we have an issue to capture the new event emitter. I am happy closing this issue now but I will let you close it in case there is further process that needs to be done on your side

**Comment by Blackbaud-AlexKingman** [comment]
Thanks @Blackbaud-LouisPujol ! I'll go ahead and close.
